# -*- coding: utf-8 -*-
"""KeyBert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vtTxlPR6IgV757xUP3f5VTEfng8sJv26
"""

pip install keybert sentence-transformers

from keybert import KeyBERT
kw_model = KeyBERT()
sentence = "What are the treatments for flu symptoms?"
keywords = kw_model.extract_keywords(sentence)
print(keywords)